<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.data2type</groupId>
    <artifactId>xspec-maven-plugin-test-issue-16</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    
    <properties>
        <saxon.version>12.9</saxon.version>
        <xmlresolver.version>6.0.23</xmlresolver.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>
    
    <dependencies>
        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>${saxon.version}</version>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.xmlresolver/xmlresolver -->
        <dependency>
            <groupId>org.xmlresolver</groupId>
            <artifactId>xmlresolver</artifactId>
            <version>${xmlresolver.version}</version>
        </dependency>
        <!--        com.xmlcalabash:xmlcalabash:3.0.49
        -->
        <dependency>
            <groupId>com.xmlcalabash</groupId>
            <artifactId>app</artifactId>
            <version>3.0.49</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>com.nkutsche</groupId>
                <artifactId>xspec-maven-plugin</artifactId>
                <version>2.2.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>run-xspec</goal>
                        </goals>
                        <configuration>
                            <!--<xspecProperties>
                                <xspec.xmlcalabash.classpath>C:\Users\Nico\.m2\repository\com\xmlcalabash\xmlcalabash\3.0.47\xmlcalabash-3.0.47.jar</xspec.xmlcalabash.classpath>
                            </xspecProperties>-->
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>io.xspec</groupId>
                        <artifactId>xspec</artifactId>
                        <version>4.0.2</version>
                        <classifier>enduser-files</classifier>
                        <type>zip</type>
                    </dependency>
                    <dependency>
                        <groupId>net.sf.saxon</groupId>
                        <artifactId>Saxon-HE</artifactId>
                        <version>${saxon.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.xmlcalabash</groupId>
                        <artifactId>app</artifactId>
                        <version>3.0.49</version>
                    </dependency>
                    <dependency>
                        <groupId>org.xmlresolver</groupId>
                        <artifactId>xmlresolver</artifactId>
                        <version>${xmlresolver.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-simple</artifactId>
                        <version>1.7.36</version>
                    </dependency>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                        <version>1.7.36</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>