<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." name="execute xspec" default="main">

    <property name="working.dir" value="${basedir}"/>
    <property name="xspec.package" value="${working.dir}/xspec-1.3.0.zip"/>
    <property name="xspec.framework" value="${working.dir}/xspec-framework/xspec-1.3.0"/>
    <property name="schxslt.root" value="${working.dir}/schxslt"/>

    <property name="temp.dir" value="${working.dir}/xspec-temp-files"/>

    <property name="project.dir" value="${basedir}/../.."/>
    <property name="build.dir" value="${project.dir}/target"/>

    <property name="test.dir" value="${project.dir}/src/test/xspec/schematron"/>

    <property name="test.type" value="s"/>
    
    <property name="fail.fast" value="false"/>

    <property name="report.dir" value="${build.dir}/xspec-reports"/>

    <property name="includes" value="**/*.xspec"/>
    <property name="excludes" value="**/*.xspec-compiled.xspec"/>

    <!--
    Surefire report
    -->
    <property name="generateSurefireReport" value="false"/>
    <property name="surefireReportDir" location="${build.dir}/surefire-reports"/>
    
    <property name="xspec.properties" value="${working.dir}/xspec.properties"/>

    <condition property="xspec.force.focus" value="#NONE" else="">
        <equals arg1="${ignore.focus}" arg2="true"/>
    </condition>

    <path id="xspec.file.list">
        <fileset dir="${test.dir}" includes="${includes}" excludes="${excludes}" erroronmissingdir="false"/>
    </path>

    <path id="xspec.framework.path">
        <pathelement path="${java.class.path}" />
    </path>
    
    <taskdef resource="net/sf/antcontrib/antlib.xml">
        <classpath>
            <pathelement location="${build.dir}/dependency/ant-contrib-1.0b3.jar"/>
        </classpath>
    </taskdef>
    
    <taskdef resource="com/nkutsche/xspecmaven/antlib.xml"/>
    
    <target name="unzip.schxslt" if="schxslt.package">
        <echo message="Unzip ${schxslt.package} to ${schxslt.root}/"/>
        <unzip src="${schxslt.package}" dest="${schxslt.root}/"/>
    </target>

    <target name="unzip" depends="unzip.schxslt">
        <echo message="Unzip ${xspec.package} to ${xspec.framework}/../" level="info"/>
        <unzip src="${xspec.package}" dest="${xspec.framework}/../"/>
    </target>

    <condition property="test.dir.exists">
        <available file="${test.dir}"/>
    </condition>

    <resourcecount property="test.dir.xspec.amount" refid="xspec.file.list"/>

    <condition property="test.dir.no.xspecs">
        <or>
            <equals arg1="false" arg2="${test.dir.exists}"/>
            <equals arg1="0" arg2="${test.dir.xspec.amount}"/>
        </or>
    </condition>

    <target name="no.xspec.message" if="test.dir.no.xspecs">
        <echo message="No XSpec files found in ${test.dir}!" level="warning"/>
        <echo message="Include patterns are: ${includes}" level="warning"/>
        <echo message="Exclude patterns are: ${excludes}" level="warning"/>
        <echo message="${toString:xspec.file.list}" level="info"/>
    </target>


    <target name="main" depends="unzip, no.xspec.message" if="test.dir.exists" description="Search for XSpec files in ${test.dir}">
        <echo message="Search for XSpec files in ${test.dir} (${test.dir.xspec.amount} XSpec files found)" level="info"/>
        <echo message="Includes: ${includes}" level="debug"/>
        <echo message="Excludes: ${excludes}" level="debug"/>
        
        <if>
            <available file="${temp.dir}"/>
            <then>
                <delete dir="${temp.dir}" quiet="true" failonerror="false"/>
            </then>
        </if>
        
        <foreach target="test" param="xspec.file">
            <path refid="xspec.file.list"/>
        </foreach>
        
        <makeurl property="temp.dir.url" file="${temp.dir}"/>
        
        <xslt in="${basedir}/build.xml"
            style="${basedir}/generate-summary.xsl"
            out="${report.dir}/index.html"
            >
            <param name="tempdir" expression="${temp.dir.url}"/>
        </xslt>
        
        <if>
            <available file="${temp.dir}/failures.txt"/>
            <then>
                <fail>XSpec tests failed. See ${report.dir}/index.html for a report.</fail>
            </then>
        </if>
        
    </target>
    
    <target name="test">
        <basename property="xspec.file.basename" file="${xspec.file}"/>
        <relativepath
            property="xspec.file.relative"
            from="${test.dir}"
            to="${xspec.file}"
        />
        

        <echo message="" level="info"/>
        <echo message="Found XSpec file ${xspec.file}" level="info"/>
        <echo message="" level="info"/>

        <echo message="project.dir       = ${project.dir}" level="debug"/>
        <echo message="xspec.framework   = ${xspec.framework}" level="debug"/>
        <echo message="xspec.xml         = ${xspec.file}" level="debug"/>
        <echo message="xspec.result.html = ${report.dir}/${xspec.file.relative}-result.html" level="debug"/>
        <echo message="xspec.dir         = ${build.dir}/xspec-temp" level="debug"/>
        
        <trycatch property="xspec.fail.message">
            <try>
                <ant antfile="${basedir}/xspec-wrapper.xml" target="xspec-wrapper" inheritall="false"
                    output="${temp.dir}/${xspec.file.basename}-xspec-stdout.log">
                    <property name="xspec.framework" value="${xspec.framework}"/>
                    <property name="xspec.file" value="${xspec.file}"/>
                    <property name="report.dir" value="${report.dir}"/>
                    <property name="xspec.file.basename" value="${xspec.file.relative}"/>
                    <property name="temp.dir" value="${temp.dir}"/>
                    <property name="generateSurefireReport" value="${generateSurefireReport}"/>
                    <property name="surefireReportDir" value="${surefireReportDir}"/>
                    <property name="xspec.properties" value="${xspec.properties}"/>
            		<property name="xspec.force.focus" value="${xspec.force.focus}"/>
                    <property name="log.file" value="${temp.dir}/${xspec.file.basename}-xspec.log"/>
                </ant>
                <echo level="info">Finalized XSpec process without any errors.</echo>
            </try>
            <catch>
                <if>
                    <istrue value="${fail.fast}"/>
                    <then>
                        <fail>${xspec.fail.message}</fail>
                    </then>
                    <else>
                        <makeurl property="xspec.url" file="${xspec.file}"/>
                        <makeurl property="css.href" file="${basedir}/xspec-report-theme-classic.css"/>
                        <echo message=";${xspec.url}" file="${temp.dir}/failures.txt" append="true"/>
                        
                        <loadfile property="xspec.result.log" srcFile="${temp.dir}/${xspec.file.basename}-xspec.log"
                            failonerror="false"/>
                        
                        <condition property="error.message" value="${xspec.result.log}" else="${xspec.fail.message}">
                            <available file="${temp.dir}/${xspec.file.basename}-xspec.log"/>
                        </condition>
                        <copy file="${basedir}/exec-error-report.html"
                            tofile="${report.dir}/${xspec.file.relative}-result-error.html" overwrite="true">
                            <filterset>
                                <filter token="title" value="${xspec.file}"/>
                                <filter token="css.href" value="${css.href}"/>
                                <filter token="error.message" value="${error.message}"/>
                            </filterset>
                        </copy>
                    </else>
                </if>
            </catch>
        </trycatch>
        
        

        <echo message="" level="info"/>
        <echo message="XSpec test finished. Report can be found here ${report.dir}/${xspec.file.basename}-result.html" level="info"/>
        <echo message="" level="info"/>
    </target>
    
    
    
</project>